# Site settings
title: Ashutosh Shukla
email: ashutosh.shukla@utexas.edu

# This description goes at the bottom of the webpage
description: >-
  Ashutosh Shukla, PhD
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ashutoshshuklaUT.github.io" # Replace username with your GitHub username
twitter_username: A_RShukla
github_username:  ashutoshshuklaUT
linkedin_username: ashutosh-ut-phd

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination for blog
paginate: 5
paginate_path: "/blog/page:num/"

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:year/:month/:day/:title/
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"